CREATE TABLE STUDENT
(StudentID INT NOT NULL,
StudentName VARCHAR(25),
CONSTRAINT Student_PK PRIMARY KEY (StudentID));

CREATE TABLE FACULTY
(FacultyID INT,
FacultyName VARCHAR(25),
CONSTRAINT FACULTY_PK PRIMARY KEY (FacultyID));

CREATE TABLE COURSE
(CourseID VARCHAR(8),
CourseName VARCHAR(15),
CONSTRAINT COURSE_PK PRIMARY KEY (CourseID) );

CREATE TABLE QUALIFIED
(FacultyID INT,
CourseID VARCHAR(8),
DateQualified DATE,
CONSTRAINT Qualified_PK PRIMARY KEY (FacultyID, CourseID),
CONSTRAINT Qualified_FK FOREIGN KEY (FacultyID) REFERENCES FACULTY(FacultyID),
CONSTRAINT Qualified_FK2 FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID));

CREATE TABLE SECTION
(SectionNo INT,
Semester VARCHAR(7),
CourseID VARCHAR(8),
CONSTRAINT Section_PK PRIMARY KEY (SectionNo),
CONSTRAINT Section_FK FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID));

CREATE TABLE REGISTRATION
(StudentID INT NOT NULL,
SectionNo INT,
CONSTRAINT Registration_PK PRIMARY KEY (StudentID, SectionNo),
CONSTRAINT Registration_FK FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID),
CONSTRAINT Registration_FK2 FOREIGN KEY (SectionNo) REFERENCES SECTION(SectionNo));


INSERT INTO COURSE(CourseID,CourseName) VALUES("ISM 3113", "Syst Analysis");
INSERT INTO COURSE(CourseID,CourseName) VALUES("ISM 3112", "Syst Design");
INSERT INTO COURSE(CourseID,CourseName) VALUES("ISM 4212", "Database");
INSERT INTO COURSE(CourseID,CourseName) VALUES("ISM 4930", "Network");

SELECT *
FROM COURSE
WHERE CourseID = "ISM 4930";

